### ISSUE TITLE
Adding meta and opengraph tags

### ISSUE THREAD

**Issue by floriansr** [MixUpTeam/MixUpFront#89]
**WHY**

We should add some metatags / opengraph for SEO issues like link is not shareable

**WHERE**

Fix this into index.html

**HOW**

- [ ] add open graph tags
- [ ] change meta description
- [ ] rebase on master
